name: 'Main'
on: push
jobs:
  prepare-evironment:
    runs-on: ubuntu-latest
    name: preapare envronment
    steps:
      - name: chackout code
        uses: actions/checkout@v3.5.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 14
      - name: prettier check
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: '--check .'
          only_changed: true
