name: release
on:
  push:
    branches:
             - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
   release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: google-github-actions/release-please-action@v3
          id: release
          with:
            release-type: node
            changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"demo-app","section":"Demo Application Updates","hidden":false},{"type":"docs","section":"Documentation Updates","hidden":false},{"type":"refactor","hidden":true},{"type":"chore","hidden":true},{"type":"ci","hidden":true},{"type":"build","hidden":true},{"type":"test","hidden":true}]'
            token: ${{secrets.RELEASE_TOKEN}}
