name: release-publish
on:
  push:
    branches:
             - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
   release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: google-github-actions/release-please-action@v3
          id: release
          with:
            release-type: node
            package-name: '@hosal/ngx-autocomplete'
            changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"perf","section":"Performance Improvements","hidden":false},{"type":"demo-app","section":"Demo Application Updates","hidden":false},{"type":"docs","section":"Documentation Updates","hidden":false},{"type":"refactor","hidden":true},{"type":"chore","hidden":true},{"type":"ci","hidden":true},{"type":"build","hidden":true},{"type":"test","hidden":true}]'
        - uses: actions/checkout@v3
          if: ${{ steps.release.outputs.release_created }}
        - uses: actions/setup-node@v3
          with:
            node-version: 20
            registry-url: 'https://registry.npmjs.org'
          if: ${{ steps.release.outputs.release_created }}
        - run: npm ci
          if: ${{ steps.release.outputs.release_created }}
        - run: npm run build
          if: ${{ steps.release.outputs.release_created }}
        - run: npm publish --access public
          working-directory: ./dist/angular-ngx-autocomplete
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          if: ${{ steps.release.outputs.release_created }}
